### ISSUE TITLE
Erro ao tentar iniciar appserver

### ISSUE THREAD

**Issue by fhfavaretto** [tgmti/ProtheusDocker#1]
Ao Rodar o comando docker-compose up e retornado o erro que o caminho e invalido segue evidencias do ocorrido.

ERROR: for appserver  Cannot create container for service appserver: invalid mount config for type "bind": bind source path does not exist:
![Captura de Tela 2020-11-05 às 13 40 25](https://user-images.githubusercontent.com/53006265/98269423-77b1c480-1f6c-11eb-9bc2-93555bc3ca82.png)

isso pode ser solucionado ?

**Comment by tgmti** [comment]
Olá Fabio.

Tem solução sim.

Para subir esta versão você precisa baixar o RPO compatível da 12.01.25 da TOTVS, e também criar a estrutura básica do diretório Protheus_Data.
No docker-compose eu usei dois volumes do tipo bind, para poder expor os diretórios APO e Protheus_Data fora do container.

Desta forma é possível alterar arquivos do sistema por fora do docker, facilitando a atualização da system e do rpo.

Você precisará criar os diretórios ./totvs_volume/apo e ./totvs_volume/protheus_data, e dentro do protheus_data, pelo menos a system e a systemload (acho que as outras ele cria automático).

Não coloquei estes arquivos no Git por dois motivos: 
1 - Tamanho dos arquivos
2 - Evitar problemas compartilhando arquivos que são de download restrito da TOTVS

![image](https://user-images.githubusercontent.com/22534389/98312513-ae113300-1fb0-11eb-8c29-96e9889a3ce6.png)

**Comment by fhfavaretto** [comment]
deu perfeitamente certo, caso eu queira  migrar para a versão 12.1.27 quais os procedimentos ?

desde já fica minha gratidão por ter compartilhado esse dockerfile, está me ajudando muito nos estudos.

**Comment by tgmti** [comment]
Opa.

Se você quiser atualizar suas imagens só localmente, ou até mesmo treinar a atualização de versão do Protheus, a forma mais simples é fazer a cópia dos arquivos normalmente, usando docker cp, depois rodar os UPDDISTR.

Com isso pronto, vc pode até salvar uma versão das máquinas, tipo `docker commit CONTAINER_HASH fhfavaretto/ProtheusAtualizado_12.01.27`

--------

Mas agora, se vc quiser passar um trabalhinho, e atualizar as imagens limpas, aí vai um passo a passo que ainda preciso publicar:

--------

Para o appserver e dbaccess, basta criar uma pasta downloads dentro deles, e colocar os arquivos compactados atualizados, com os nomes que estão no Dockerfile (ou mudar no Dockerfile)

![image](https://user-images.githubusercontent.com/22534389/99394925-79f61600-28be-11eb-931d-c98585b2a057.png)

Aí rodar um `docker build -t [usuario/nomeimagem] .` pra cada um deles

--------

O License é um pouco mais complicadinho, pq tem que subir uma máquina "construtora" e rodar o aplicativo Java, pois não consegui passar os comandos para o mesmo através de script.

O passo a passo está no [license/DockerfileBuilder](https://github.com/tgmti/ProtheusDocker/blob/master/license/DockerfileBuilder)

--------

Para atualizar a imagem do banco

- subir uma máquina com banco zerado (apaga as linhas de restore do [Dockerfile](https://github.com/tgmti/ProtheusDocker/blob/master/postgres/Dockerfile#L13)

- Subir o ambiente completo, entrar no sistema, que ele vai criar as tabelas.

- Exportar o backup do banco

  - Conectar no Container: `docker exec -ti HASH_CONTAINER_BANCO bash`
  - Gerar um Dump do banco: `pg_dump -U protheus -F t protheus > ~/pgProtheusBackup.tar`
  - Compactar o Backup: `tar -czf pgProtheusBackup.tar.gz pgProtheusBackup.tar`
  - Copiar esse arquivo pgProtheusBackup.tar.gz pra fora do container com `docker cp`
  - Ajustar o Dockerfile do Postgre, pra apontar pra esse novo arquivo [aqui](https://github.com/tgmti/ProtheusDocker/blob/master/postgres/restore.sh#L5) e [aqui](https://github.com/tgmti/ProtheusDocker/blob/master/postgres/Dockerfile#L13)

Vai dar um trabalhinho, mas se vc fizer isso, já me manda um PR com esse novo arquivo, que atualizo a imagem no dockerhub também (outra coisa que preciso fazer automatizado).

--------

A minha intenção é mexer no esquema pra fazer uma atualização mais automatizada. 

Tanto que montei os Dockerfile com versão agnóstica. Com exceção do postgres (tenho que mudar isso).

Fiz uma coisa parecida quando trabalhava na TOTVS, mas lá eu tinha acesso ao arte.engpro.totvs.com.br, daí a imagem atualizava automaticamente quando fazia o build.

A ideia é que, para montar uma nova base, basta dar um docker build, com os arquivos atualizados nas pastas de appserver e tals.

Também fiz uma versão 12.01.27 com SqLite na minha máquina (só usa appserver e License daí), e ainda estou decidindo como fazer pra publicar ...

**Comment by fhfavaretto** [comment]
ah sim entendi agradeço então fico no aguardo por novas features deste projeto. obrigado

**Comment by fhfavaretto** [comment]
Bom dia, tudo bem ?

estou tentando atualizar o appserver, e vim conferir como realizar os procedimentos ali vc disse para criar uma pasta "Para o appserver e dbaccess, basta criar uma pasta downloads dentro deles, e colocar os arquivos compactados atualizados, com os nomes que estão no Dockerfile (ou mudar no Dockerfile)"

a onde preciso criar essas pastas ?

**Comment by tgmti** [comment]
A pasta Downloads deve estar dentro da pasta onde está o Dockerfile.
tipo appserver/Downloads

**Comment by fhfavaretto** [comment]
e para o dbacess ? como posso realizar o procedimento ?

**Comment by tgmti** [comment]
Sim... mesmo esquema...

salva o arquivo na pasta Downloads, dentro de DbAccess, com o mesmo nome que está no Dockerfile dele

"""DBACCESS_LINUX_X64_BUILD.TAR.GZ"""

![image](https://user-images.githubusercontent.com/22534389/111685213-66c06c00-8806-11eb-8e66-fe4f214fad1f.png)

**Comment by fhfavaretto** [comment]
Bom dia, após realizar este comando para atualização `docker build -t tgmti:totvs-appserver appserver/`
o mesmo executa o build porém me retorna este problema. sabes o que possa ter feito errado ?
<img width="1440" alt="Captura de Tela 2021-03-19 às 08 26 02" src="https://user-images.githubusercontent.com/53006265/111773672-3a9bfe00-888d-11eb-8b4b-9c740b63c81e.png">

**Comment by tgmti** [comment]
Erro de permissão ao tentar rodar o Script

![image](https://user-images.githubusercontent.com/22534389/111778900-26a7ca80-8894-11eb-920c-a19b549be94f.png)


Vc está fazendo o build a partir de um  host Windows ou Linux?

Talvez resolva adicionando uma linha no Dockerfile, pra dar um chmod 777 no setup.sh

Se não for, deve ser alguma das operações dentro dele que deu problema.

Geralmente, nestes casos, eu entro com "docker run -ti ID_CONTAINER_INTERMEDIARIO bash"

aÍ tento rodar na mão ... pra ver se apresenta o mesmo erro ....
